(function(){var h={},mt={},c={id:"848eb8a2a8c03f03b366c3e95d6e6627",dm:["vote.huanqiu.com"],js:"tongji.baidu.com/hm-web/js/",etrk:["%7b%22https%3a%5c%2f%5c%2fvote.huanqiu.com%5c%2faf96c%5c%2f*%22%3a%5b%22%23buttSign%22%2c%22%23share%22%5d%7d"],cetrk:[],cptrk:[],icon:'',ctrk:[],nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'1156EC0ACE8C2D08',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var s=void 0,v=!0,w=null,y=!1;mt.cookie={};mt.cookie.set=function(a,b,d){var e;d.U&&(e=new Date,e.setTime(e.getTime()+d.U));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.Sc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:w};
mt.cookie.uc=function(a,b){try{var d="Hm_ck_"+ +new Date;mt.cookie.set(d,"is-cookie-enabled",{domain:a,path:b,U:s});var e="is-cookie-enabled"===mt.cookie.get(d)?"1":"0";mt.cookie.set(d,"",{domain:a,path:b,U:-1});return e}catch(f){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.eb=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.J=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.I=function(a,b){var d=y;if(a==w||!mt.lang.d(a,"Array")||b===s)return d;if(Array.prototype.indexOf)d=-1!==a.indexOf(b);else for(var e=0;e<a.length;e++)if(a[e]===b){d=v;break}return d};mt.url={};mt.url.m=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:w};
mt.url.Oc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:w};mt.url.Wb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):w};mt.url.P=function(a){return(a=mt.url.Wb(a))?a.replace(/:\d+$/,""):a};mt.url.Ha=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):w};
(function(){var a=mt.lang,b=mt.url;mt.f={};mt.f.Ea=function(d){return document.getElementById(d)};mt.f.Fa=function(d){if(!d)return w;try{d=String(d);if(0===d.indexOf("!HMCQ!"))return d;if(0===d.indexOf("!HMCC!"))return document.querySelector(d.substring(6,d.length));for(var e=d.split(">"),a=document.body,b=e.length-1;0<=b;b--)if(-1<e[b].indexOf("#")){var g=e[b].split("#")[1];(a=document.getElementById(g))||(a=document.getElementById(decodeURIComponent(g)));e=e.splice(b+1,e.length-(b+1));break}for(d=
0;a&&d<e.length;){var l=String(e[d]).toLowerCase();if(!("html"===l||"body"===l)){var b=0,n=e[d].match(/\[(\d+)\]/i),g=[];if(n)b=n[1]-1,l=l.split("[")[0];else if(1!==a.childNodes.length){for(var t=0,u=0,p=a.childNodes.length;u<p;u++){var r=a.childNodes[u];1===r.nodeType&&r.nodeName.toLowerCase()===l&&t++;if(1<t)return w}if(1!==t)return w}for(t=0;t<a.childNodes.length;t++)1===a.childNodes[t].nodeType&&a.childNodes[t].nodeName.toLowerCase()===l&&g.push(a.childNodes[t]);if(!g[b])return w;a=g[b]}d++}return a}catch(k){return w}};
mt.f.Ha=function(a,e){var f=[],b=[];if(!a)return b;for(;a.parentNode!=w;){for(var g=0,l=0,n=a.parentNode.childNodes.length,t=0;t<n;t++){var u=a.parentNode.childNodes[t];if(u.nodeName===a.nodeName&&(g++,u===a&&(l=g),0<l&&1<g))break}if((n=""!==a.id)&&e){f.unshift("#"+encodeURIComponent(a.id));break}else n&&(n="#"+encodeURIComponent(a.id),n=0<f.length?n+">"+f.join(">"):n,b.push(n)),f.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<g?"["+l+"]":""));a=a.parentNode}b.push(f.join(">"));return b};
mt.f.na=function(a){return(a=mt.f.Ha(a,v))&&a.length?String(a[0]):""};mt.f.$b=function(a){return mt.f.Ha(a,y)};mt.f.Xa=function(a){var e;for(e="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==e)return a;return w};mt.f.Sb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Ya=function(a){var e={top:0,left:0};if(!a)return e;var b=mt.f.Sb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(e=a.getBoundingClientRect());return{top:e.top+(window.pageYOffset||b.scrollTop)-
(b.clientTop||0),left:e.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};mt.f.getAttribute=function(a,e){var b=a.getAttribute&&a.getAttribute(e)||w;if(!b&&a.attributes&&a.attributes.length)for(var m=a.attributes,g=m.length,l=0;l<g;l++)m[l].nodeName===e&&(b=m[l].nodeValue);return b};mt.f.X=function(a){var e="document";a.tagName!==s&&(e=a.tagName);return e.toLowerCase()};mt.f.ec=function(b){var e="";b.textContent?e=a.trim(b.textContent):b.innerText&&(e=a.trim(b.innerText));e&&(e=e.replace(/\s+/g,
" ").substring(0,255));return e};mt.f.W=function(d,e){var f;a.J(d)&&0===String(d).indexOf("!HMCQ!")?(f=String(d),f=b.m(document.location.href,f.substring(6,f.length))):a.J(d)||(f=mt.f.X(d),"input"===f&&e&&("button"===d.type||"submit"===d.type)?f=a.trim(d.value)||"":"input"===f&&!e&&"password"!==d.type?f=a.trim(d.value)||"":"img"===f?(f=mt.f.getAttribute,f=f(d,"alt")||f(d,"title")||f(d,"src")):f="body"===f||"html"===f?["(hm-default-content-for-",f,")"].join(""):mt.f.ec(d));return String(f||"").substring(0,
255)};(function(){(mt.f.lb=function(){function a(){if(!a.qa){a.qa=v;for(var b=0,e=m.length;b<e;b++)m[b]()}}function e(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(e,1);return}a()}var b=y,m=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,y);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!b)if(b=v,"complete"===document.readyState)a.qa=v;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,y),window.addEventListener("load",a,y);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var l=y;try{l=window.frameElement==w}catch(n){}document.documentElement.doScroll&&l&&e()}})();return function(b){a.qa?b():m.push(b)}}()).qa=y})();return mt.f})();mt.event={};
mt.event.e=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,y)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=y};
(function(){var a=mt.event;mt.g={};mt.g.oa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.Xb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.g.Pc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return y}};mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();
mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.yc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.bc=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.ab=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.H=
function(){return mt.g.bc()+mt.g.ab()};mt.g.vb=0;mt.g.gc=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.g.orientation=0;(function(){function b(){var a=0;window.orientation!==s&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(a=screen.orientation.angle);mt.g.orientation=a;mt.g.vb=mt.g.gc()}b();a.e(window,"orientationchange",b)})();return mt.g})();mt.A={};
mt.A.parse=function(a){return(new Function("return ("+a+")"))()};
mt.A.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var e=d[a];if(e)return e;e=a.charCodeAt();return"\\u00"+Math.floor(e/16).toString(16)+(e%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===w)return"null";if(e instanceof Array){var f=["["],d=e.length,g,l,n;for(l=0;l<d;l++)switch(n=e[l],typeof n){case "undefined":case "function":case "unknown":break;default:g&&f.push(","),f.push(mt.A.stringify(n)),g=1}f.push("]");return f.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+b(e.getMonth()+1)+"-"+b(e.getDate())+"T"+b(e.getHours())+":"+b(e.getMinutes())+":"+b(e.getSeconds())+'"';g=["{"];l=mt.A.stringify;for(d in e)if(Object.prototype.hasOwnProperty.call(e,d))switch(n=
e[d],typeof n){case "undefined":case "unknown":case "function":break;default:f&&g.push(","),f=1,g.push(l(d)+":"+l(n))}g.push("}");return g.join("")}}}();mt.localStorage={};mt.localStorage.xa=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return y}return v};
mt.localStorage.set=function(a,b,d){var e=new Date;e.setTime(e.getTime()+d||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.xa()&&(mt.localStorage.l.expires=e.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.xa())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(e){}return w};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.xa())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):w}catch(b){return w}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.rb={};mt.rb.log=function(a,b){var d=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=d;d.onload=function(){d.onload=w;d=window[e]=w;b&&b(a)};d.src=a};mt.Pa={};
mt.Pa.fc=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
mt.Pa.Mc=function(a,b,d,e,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+d+'" height="'+e+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+d+'" height="'+e+'" src="'+b+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};
h.z={nc:"http://tongji.baidu.com/hm-web/welcome/ico",Oa:"hm.baidu.com/hm.gif",Bb:/^(tongji|hmcdn).baidu.com$/,ub:"tongji.baidu.com",kc:"hmmd",lc:"hmpl",Jc:"utm_medium",jc:"hmkw",Lc:"utm_term",hc:"hmci",Ic:"utm_content",mc:"hmsr",Kc:"utm_source",ic:"hmcu",Hc:"utm_campaign",Q:0,M:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",sa:"https:",Qc:0,Hb:6E5,Rc:6E5,zc:5E3,Ib:5,R:1024,Gb:1,da:2147483647,tb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
Z:v,Va:["a","input","button"],Sa:{id:"data-hm-id",ka:"data-hm-class",ha:"data-hm-xpath",content:"data-hm-content",va:"data-hm-tag",link:"data-hm-link"},Ua:"data-hm-enabled",Ta:"data-hm-disabled",wc:"https://hmcdn.baidu.com/static/tongji/plugins/",jb:["UrlChangeTracker","OcpcCbHm"]};(function(){var a={F:{},e:function(a,d){this.F[a]=this.F[a]||[];this.F[a].push(d)},N:function(a,d){this.F[a]=this.F[a]||[];for(var e=this.F[a].length,f=0;f<e;f++)this.F[a][f](d)}};return h.s=a})();
(function(){var a=mt.lang,b=/^https?:\/\//,d={Rb:function(a){var b;try{b=JSON.parse(decodeURIComponent(a[0]))}catch(d){}return b},fb:function(a,f){var d=h.c&&h.c.b&&h.c.b.u||document.location.href;b.test(a)||(d=d.replace(b,""));a=a.replace(/\/$/,"");d=d.replace(/\/$/,"");f&&(d=d.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+a.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(d)},G:function(e,b){var m=d.Rb(e);if(!a.d(m,"Undefined")){if(a.d(m,"Array")){for(var g=0;g<m.length;g++)if(d.fb(m[g],
b))return v;return y}if(a.d(m,"Object")){var g=[],l;for(l in m)m.hasOwnProperty(l)&&d.fb(l,b)&&(g=g.concat(m[l]));return g}}}};return h.S=d})();
(function(){function a(a,e){var f=document.createElement("script");f.charset="utf-8";b.d(e,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=w,e()}:f.onload=function(){e()});f.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(f,m)}var b=mt.lang;return h.load=a})();
(function(){function a(){var a="";if(h.c.b.nv){a=encodeURIComponent(document.referrer);try{window.sessionStorage?d.set("Hm_from_"+c.id,a):b.set("Hm_from_"+c.id,a,864E5)}catch(f){}}else try{a=(window.sessionStorage?d.get("Hm_from_"+c.id):b.get("Hm_from_"+c.id))||""}catch(m){}return a}var b=mt.localStorage,d=mt.sessionStorage;return h.Nc=a})();
(function(){var a=h.z,b={init:function(){if(""!==c.icon){var b=c.icon.split("|"),e=a.nc+"?s="+c.id,f="https://hmcdn.baidu.com/static"+b[0]+".gif";document.write("swf"===b[1]||"gif"===b[1]?'<a href="'+e+'" target="_blank"><img border="0" src="'+f+'" width="'+b[2]+'" height="'+b[3]+'"></a>':'<a href="'+e+'" target="_blank">'+b[0]+"</a>")}}};h.s.e("pv-b",b.init);return b})();
(function(){var a=mt.cookie,b=mt.localStorage,d=mt.sessionStorage,e={getData:function(e){try{return a.get(e)||d.get(e)||b.get(e)}catch(m){}},setData:function(f,m,g){try{a.set(f,m,{domain:e.V(),path:e.ma(),U:g}),g?b.set(f,m,g):d.set(f,m)}catch(l){}},removeData:function(f){try{a.set(f,"",{domain:e.V(),path:e.ma(),U:-1}),d.remove(f),b.remove(f)}catch(m){}},$:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var e=a.indexOf(b);return-1<e&&e+b.length===a.length},ra:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},V:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(e.$(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ma:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&e.ra(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.Ca=e})();
(function(){var a=mt.lang,b=mt.A,d=h.Ca,e={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},f={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},m=["session","user"],g="Hm_up_"+c.id,l={init:function(){l.rc()},rc:function(){try{var n=b.parse(decodeURIComponent(d.getData(g)));a.d(n,"Object")&&(e.user=n)}catch(f){}},B:function(a){var b={};e[a]!==s&&(b=e[a]);a=this.Ia();for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a},Ia:function(){for(var a={},b,d=m.length-
1;0<=d;d--){b=e[m[d]];for(var p in b)b.hasOwnProperty(p)&&(a[p]=b[p])}return a},setProperty:function(d,f,g){var p=e[d];if(a.d(p,"Object")&&a.d(f,"Object")){for(var r in f)if(f.hasOwnProperty(r)){var k=a.h(String(r));if(g||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var q=f[r];if(q==w)delete p[k];else{if(a.d(q,"Object")||a.d(q,"Array"))q=b.stringify(q);q=a.h(String(q));l.tc(d,k,q)&&(p[k]={value:q,scope:l.$a(d)})}}}"user"===d&&l.Ma()}},w:function(b){b!==s&&("userId"===
b&&a.d(e.user,"Object")?(delete e.user.uid_,l.Ma()):"user"===b&&a.d(e.user,"Object")?(b=e.user.uid_,e.user=b===s?{}:{uid_:b},l.Ma()):e[b]!==s&&(e[b]={}))},Ma:function(){try{d.setData(g,encodeURIComponent(b.stringify(e.user)),c.age)}catch(a){}},tc:function(a,b,d){var p=v,f=e[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(d)).length)p=y;else{var k=f[b];f[b]={value:d,scope:l.$a(a)};a=l.L(l.B(a));2048<encodeURIComponent(a).length&&(k!==s?f[b]=k:delete f[b],p=y)}return p},
L:function(a){var b=[],e,d;for(d in a)a.hasOwnProperty(d)&&(e=[d,a[d].value],(1===a[d].scope||2===a[d].scope)&&e.push(a[d].scope),b.push(e.join("*")));return b.join("!")},$a:function(a){a=f[a];return a!==s?a:f.others}};return h.O=l})();
(function(){var a=mt.f,b=mt.lang,d=h.s,e=h.S,f=h.O,m=f.L;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var g={ib:{},wa:{},init:function(){for(var a,d=e.G(c.cptrk)||[],f=0;f<d.length;f++)if(a=d[f],a.a!==s&&b.d(a.a,"Object")){a=a.a;for(var m in a)a.hasOwnProperty(m)&&(g.wa[m]=String(a[m]))}},hb:function(){var b,e,d;for(d in g.wa)if(g.wa.hasOwnProperty(d)&&g.ib[d]===s&&(b=g.wa[d],b=a.Fa(b)))e=e===s?{}:e,e[d]=a.W(b,y),g.ib[d]=v;return e},Ja:function(){var a=g.hb();a&&g.Bc(a)},qc:function(){"MutationObserver"in
window&&document.body?(new MutationObserver(g.Ja)).observe(document.body,{childList:v,subtree:v}):window.setInterval(g.Ja,15E3)},Bc:function(a){if(b.d(a,"Object")){f.setProperty("pageview",a);a=h.c.b.p;var e=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=m(f.B("pageview"));h.c.i();h.c.b.p=a;h.c.b.ep=e;f.w("pageview")}}};g.init();d.e("pv-b",function(){var a=g.hb();a&&f.setProperty("pageview",a)});g.qc();a.lb(g.Ja)}})();
(function(){var a=mt.lang,b=mt.f,d=h.S,e={T:function(a,m){return function(g){var l=g.target||g.srcElement;if(l){var n=d.G(m)||[],t=l.getAttribute(a.ia);g=g.clientX+":"+g.clientY;if(t&&t===g)l.removeAttribute(a.ia);else if(0<n.length&&(l=b.$b(l))&&l.length)if(n=l.length,t=l[l.length-1],1E4>n*t.split(">").length)for(t=0;t<n;t++)e.qb(a,l[t]);else e.qb(a,t)}}},qb:function(b,e){for(var d={},l=String(e).split(">").length,n=0;n<l;n++)d[e]="",e=e.substring(0,e.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.Ba)&&
b.Ba(d)},mb:function(a,b){return function(e){(e.target||e.srcElement).setAttribute(a.ia,e.clientX+":"+e.clientY);a&&a.o&&(b?a.o(b):a.o("#"+encodeURIComponent(this.id),e.type))}}};return h.la=e})();
(function(){var a=mt.f,b=mt.event,d=h.S,e=h.la,f={ia:"HM_fix",Aa:function(){b.e(document,"click",e.T(f,c.etrk));for(var m=d.G(c.etrk)||[],g=0;g<m.length;g++){var l=m[g];-1===l.indexOf(">")&&(0===l.indexOf("#")&&(l=l.substring(1)),(l=a.Ea(l))&&b.e(l,"click",e.mb(f)))}},Ba:function(a){for(var b=d.G(c.etrk)||[],e=0;e<b.length;e++){var n=b[e];a.hasOwnProperty(n)&&f.o(n)}},o:function(a,b){h.c.b.et=1;h.c.b.ep="{id:"+a+",eventType:"+(b||"click")+"}";h.c.i()}};h.s.e("pv-b",f.Aa);return f})();
(function(){var a=mt.f,b=mt.event,d=mt.lang,e=h.z,f=h.S,m=h.la,g=h.O,l=g.L,n={ia:"HM_ce",Aa:function(){if(c.cetrk&&0<c.cetrk.length){b.e(document,"click",m.T(n,c.cetrk));for(var e=f.G(c.cetrk)||[],d=0,p=e.length;d<p;d++){var r=e[d],k=r.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.Ea(k))&&b.e(k,"click",m.mb(n,r)))}}},Ba:function(a){for(var b=f.G(c.cetrk)||[],e=0;e<b.length;e++){var d=b[e],k=n.Ub(d.p,a);k&&n.o(d,k)}},Ub:function(a,b){a=String(a);if(0<a.indexOf("*")){var e=
RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),d;for(d in b)if(b.hasOwnProperty(d)&&e.test(d))return d;return w}return b.hasOwnProperty(a)?a:w},o:function(b,e){h.c.b.et=7;var f=b&&b.k||"",f=d.h(f),r={};if(b&&b.a&&d.d(b.a,"Object")){var k=b.a,q;for(q in k)if(k.hasOwnProperty(q)){var x=n.ac(k[q]||"",e),x=x?a.W(x,y):"";r[q]=x}}r=n.Pb(r,e||b&&b.p);r._iden=f;g.setProperty("customEvent",r);h.c.b.ep="";h.c.b.p=l(g.B("customEvent"));h.c.i();h.c.b.p="";g.w("customEvent")},
Pb:function(b,d){var f=a.Fa(d),g=e.Sa;f&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(f,g.id)||a.getAttribute(f,"id")||"",b.ec_=a.getAttribute(f,g.ka)||a.getAttribute(f,"class")||"",b.ex_=a.getAttribute(f,g.ha)||a.na(f),b.en_=a.getAttribute(f,g.content)||a.W(f,v),b.et_=a.getAttribute(f,g.va)||a.X(f),b.el_=a.getAttribute(f,g.link)||a.getAttribute(f,"href")||""):(b.ex_=a.getAttribute(f,g.ha)||a.na(f),b.en_=a.getAttribute(f,g.content)||a.W(f,v)));return b},ac:function(b,e){b=String(b);e=String(e);if(0<
b.indexOf("*")){var d=/.*\[(\d+)\]$/.exec(e);b=b.replace("*",d?d[1]:"1")}return a.Fa(b)}};h.s.e("pv-b",n.Aa);return n})();
(function(){var a=mt.f,b=mt.lang,d=mt.event,e=mt.g,f=h.z,m=h.S,g=[],l={wb:function(){c.ctrk&&0<c.ctrk.length&&(d.e(document,"mouseup",l.Fb()),d.e(window,"unload",function(){l.ta()}),setInterval(function(){l.ta()},f.Hb))},Fb:function(){return function(a){if(m.G(c.ctrk,v)&&(a=l.Qb(a),""!==a)){var b=(f.sa+"//"+f.Oa+"?"+h.c.pb().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(f.da+"").length>f.R||(b+encodeURIComponent(g.join("!")+(g.length?"!":"")).length+(f.da+"").length>f.R&&l.ta(),g.push(a),
(g.length>=f.Ib||/\*a\*/.test(a))&&l.ta())}}},Qb:function(d){var g=d.target||d.srcElement;if(0===f.Gb){var m=(g.tagName||"").toLowerCase();if("embed"==m||"object"==m)return""}var p;e.oa?(p=Math.max(document.documentElement.scrollTop,document.body.scrollTop),m=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),m=d.clientX+m,p=d.clientY+p):(m=d.pageX,p=d.pageY);d=l.Yb(d,g,m,p);var r=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:m-=
r/2;break;case 2:m-=r}r=[];r.push(m);r.push(p);r.push(d.ca);r.push(d.ea);r.push(d.xc);r.push(b.h(d.vc));r.push(d.ga);r.push(d.Y);(g="a"===(g.tagName||"").toLowerCase()?g:a.Xa(g))?(r.push("a"),r.push(b.h(encodeURIComponent(g.href)))):r.push("b");return r.join("*")},Yb:function(d,f,g,p){d=a.na(f);var r=0,k=0,q=0,x=0;if(f&&(r=f.offsetWidth||f.clientWidth,k=f.offsetHeight||f.clientHeight,x=a.Ya(f),q=x.left,x=x.top,b.d(f.getBBox,"Function")&&(k=f.getBBox(),r=k.width,k=k.height),"html"===(f.tagName||"").toLowerCase()))r=
Math.max(r,f.clientWidth),k=Math.max(k,f.clientHeight);return{ca:Math.round(100*((g-q)/r)),ea:Math.round(100*((p-x)/k)),xc:e.orientation,vc:d,ga:r,Y:k}},ta:function(){0!==g.length&&(h.c.b.et=2,h.c.b.ep=g.join("!"),h.c.i(),g=[])}};h.s.e("pv-b",l.wb);return l})();
(function(){var a=mt.lang,b=mt.f,d=mt.event,e=mt.g,f=h.z,m=h.s,g=h.O,l=g.L,n=+new Date,t=[],u={T:function(){return function(e){if(h.c&&h.c.Z&&c.aet&&c.aet.length){var d=e.target||e.srcElement;if(d){var k=h.c.Va,q=b.getAttribute(d,f.Ua)!=w?v:y;if(b.getAttribute(d,f.Ta)==w)if(q)u.ya(u.Ga(d,e));else{var x=b.X(d);if(a.I(k,"*")||a.I(k,x))u.ya(u.Ga(d,e));else for(;d.parentNode!=w;){var q=d.parentNode,x=b.X(q),z="a"===x&&a.I(k,"a")?v:y,x="button"===x&&a.I(k,"button")?v:y,A=b.getAttribute(q,f.Ua)!=w?v:y;
if(b.getAttribute(q,f.Ta)==w&&(z||x||A)){u.ya(u.Ga(q,e));break}d=d.parentNode}}}}}},Ga:function(d,g){var k={},q=f.Sa;k.id=b.getAttribute(d,q.id)||b.getAttribute(d,"id")||"";k.ka=b.getAttribute(d,q.ka)||b.getAttribute(d,"class")||"";k.ha=b.getAttribute(d,q.ha)||b.na(d);k.content=b.getAttribute(d,q.content)||b.W(d,v);k.va=b.getAttribute(d,q.va)||b.X(d);k.link=b.getAttribute(d,q.link)||b.getAttribute(d,"href")||"";k.type=g.type||"click";q=a.eb(d.offsetTop)?d.offsetTop:0;"click"===g.type?q=e.oa?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.gb&&g.gb.changedTouches)&&(q=g.gb.changedTouches[0].pageY);k.Gc=q;q=this.Tb(g);k.ca=q.ca||0;k.ea=q.ea||0;k.ga=q.ga||0;k.Y=q.Y||0;k.Qa=q.Qa||"b";return k},Tb:function(d){var f=d.target||d.srcElement,g;if(e.oa){var q=Math.max(document.documentElement.scrollTop,document.body.scrollTop);g=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);g=d.clientX+g;d=d.clientY+q}else g=d.pageX,
d=d.pageY;var x=q=0,z=0,A=0;if(f&&(q=f.offsetWidth||f.clientWidth,x=f.offsetHeight||f.clientHeight,A=b.Ya(f),z=A.left,A=A.top,a.d(f.getBBox,"Function")&&(x=f.getBBox(),q=x.width,x=x.height),"html"===(f.tagName||"").toLowerCase()))q=Math.max(q,f.clientWidth),x=Math.max(x,f.clientHeight);return{ca:Math.round(100*((g-z)/q)),ea:Math.round(100*((d-A)/x)),ga:q,Y:x,Qa:("a"===(f.tagName||"").toLowerCase()?f:b.Xa(f))?"a":"b"}},ya:function(b){var d=a.h;b=[+new Date-(h.c.aa!==s?h.c.aa:n),d(b.id),d(b.ka),d(b.va),
d(b.ha),d(b.link),d(b.content),b.type,b.Gc,b.ca,b.ea,b.ga,b.Y,b.Qa].join("*");u.za(b);a.d(this.fa(),"Function")&&this.fa()()},za:function(a){a.length>f.R||(encodeURIComponent(t.join("!")+a).length>f.R&&(u.o(t.join("!")),t=[]),t.push(a))},o:function(a){h.c.b.et=5;h.c.b.ep=a;g.setProperty("autoEventTracking",{view_h_:e.H()},v);h.c.b.p=l(g.B("autoEventTracking"));h.c.i();h.c.b.p="";g.setProperty("autoEventTracking",{view_h_:w},v)},fa:function(){return function(){t&&t.length&&(u.o(t.join("!")),t=[])}}};
a.J(c.aet)&&""!==c.aet&&m.e("pv-b",function(){d.e(document,"click",u.T());"ontouchend"in document&&d.e(window,"touchend",u.T());d.e(window,"unload",u.fa())});return u})();
(function(){var a=mt.lang,b=mt.event,d=mt.g,e=h.z,f=h.s,m=h.O,g=m.L,l=+new Date,n=[],t=w,u={zb:function(){a.J(c.aet)&&""!==c.aet&&setInterval(u.ob,e.zc)},ob:function(){var a=d.H();0<a-h.c.b.vl&&(h.c.b.vl=a)}},p={Lb:function(){return function(){h.c&&(h.c.Z&&c.aet&&c.aet.length)&&(window.clearTimeout(t),t=window.setTimeout(function(){p.yb(d.H())},150))}},yb:function(a){p.za([+new Date-(h.c.aa!==s?h.c.aa:l),a].join("*"))},za:function(a){if(encodeURIComponent(n.join("!")+a).length>e.R||3<n.length)p.o(n.join("!")),
n=[];n.push(a)},o:function(a){u.ob();h.c.b.et=6;h.c.b.vh=d.ab();h.c.b.ep=a;m.setProperty("autoEventTracking",{view_h_:d.H()},v);h.c.b.p=g(m.B("autoEventTracking"));h.c.i();h.c.b.p="";m.setProperty("autoEventTracking",{view_h_:w},v)},fa:function(){return function(){n&&n.length&&(p.o(n.join("!")),n=[])}}};a.J(c.aet)&&""!==c.aet&&f.e("pv-b",function(){b.e(window,"scroll",p.Lb());b.e(window,"unload",p.fa());u.zb()});return p})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.Da.Zb()+","+h.Da.Vb();h.c.b.hca=c.hca;h.c.i()}}function b(){clearTimeout(z);var a;q&&(a="visible"==document[q]);x&&(a=!document[x]);l="undefined"==typeof a?v:a;if((!g||!n)&&l&&t)k=v,p=+new Date;else if(g&&n&&(!l||!t))k=y,r+=+new Date-p;g=l;n=t;z=setTimeout(b,100)}function d(a){var b=document,q="";if(a in b)q=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var f=d[e]+a.charAt(0).toUpperCase()+a.slice(1);
if(f in b){q=f;break}}return q}function e(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))t="focus"==a.type||"focusin"==a.type?v:y,b()}var f=mt.event,m=h.s,g=v,l=v,n=v,t=v,u=+new Date,p=u,r=0,k=v,q=d("visibilityState"),x=d("hidden"),z;b();(function(){var a=q.replace(/[vV]isibilityState/,"visibilitychange");f.e(document,a,b);f.e(window,"pageshow",b);f.e(window,"pagehide",b);"object"==typeof document.onfocusin?(f.e(document,"focusin",e),f.e(document,"focusout",e)):(f.e(window,
"focus",e),f.e(window,"blur",e))})();h.Da={Zb:function(){return+new Date-u},Vb:function(){return k?+new Date-p+r:r}};m.e("pv-b",function(){f.e(window,"unload",a())});m.e("duration-send",a());m.e("duration-done",function(){p=u=+new Date;r=0});return h.Da})();
(function(){var a=mt.lang,b=h.z,d=h.load,e={pc:function(e){if((window._dxt===s||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var m=h.c.V();d([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(m)].join(""),e)}},Fc:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.Jb=e})();
(function(){function a(a,b,d,e){if(!(a===s||b===s||e===s)){if(""===a)return[b,d,e].join("*");a=String(a).split("!");for(var f,g=y,k=0;k<a.length;k++)if(f=a[k].split("*"),String(b)===f[0]){f[1]=d;f[2]=e;a[k]=f.join("*");g=v;break}g||a.push([b,d,e].join("*"));return a.join("!")}}function b(a){for(var d in a)if({}.hasOwnProperty.call(a,d)){var f=a[d];e.d(f,"Object")||e.d(f,"Array")?b(f):a[d]=String(f)}}var d=mt.url,e=mt.lang,f=mt.A,m=mt.g,g=h.z,l=h.s,n=h.Jb,t=h.load,u=h.Ca,p=h.O,r=p.L,k={ba:[],ua:0,
La:y,D:{Ra:"",page:""},init:function(){k.j=0;p.init();l.e("pv-b",function(){k.Kb();k.Mb()});l.e("pv-d",function(){k.Nb();k.D.page=""});l.e("stag-b",function(){h.c.b.api=k.j||k.ua?k.j+"_"+k.ua:"";h.c.b.ct=[decodeURIComponent(u.getData("Hm_ct_"+c.id)||""),k.D.Ra,k.D.page].join("!")});l.e("stag-d",function(){h.c.b.api=0;k.j=0;k.ua=0})},Kb:function(){var a=window._hmt||[];if(!a||e.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var d=arguments[b];
e.d(d,"Array")&&(a.cmd[a.id].push(d),"_setAccount"===d[0]&&(1<d.length&&/^[0-9a-f]{31,32}$/.test(d[1]))&&(d=d[1],a.id=d,a.cmd[d]=a.cmd[d]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Mb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,e=0,f=b.length;e<f;e++){var g=b[e];d.test(g[0])?k.ba.push(g):k.Na(g)}a.cmd[c.id]={push:k.Na}},Nb:function(){if(0<k.ba.length)for(var a=0,b=k.ba.length;a<b;a++)k.Na(k.ba[a]);k.ba=
w},Na:function(a){var b=a[0];if(k.hasOwnProperty(b)&&e.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&(k.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],y===a||v===a))k.j|=2,h.c.bb=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(k.j|=4,h.c.b.sn=h.c.Za(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=m.H(),h.c.b.kb=0,h.c.Ka?(h.c.b.nv=0,h.c.b.st=4):h.c.Ka=v,k.La||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=g.protocol+
"//"+document.location.host+a[1],h.c.b.p=r(p.B("pageview")),h.c.i(),h.c.b.p="",h.c.aa=+new Date,p.w("pageview"))},_trackEvent:function(a){2<a.length&&(k.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=e.h(a[1])+"*"+e.h(a[2])+(a[3]?"*"+e.h(a[3]):"")+(a[4]?"*"+e.h(a[4]):""),h.c.b.p=r(p.Ia()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){k.ua++;for(var f=(h.c.b.cv||"*").split("!"),g=f.length;g<b-1;g++)f.push("*");f[b-1]=d+"*"+e.h(a[2])+"*"+
e.h(a[3]);h.c.b.cv=f.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?u.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):u.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var d=e.h(b[1]);b=e.h(b[2]);if(d!==s&&b!==s){var f=decodeURIComponent(u.getData("Hm_ct_"+c.id)||""),f=a(f,d,1,b);u.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var d=e.h(b[1]);b=e.h(b[2]);if(d!==s&&b!==s){var f=k.D.Ra,
f=a(f,d,2,b);k.D.Ra=f}}},_setPageTag:function(b){if(!(3>b.length)){var d=e.h(b[1]);b=e.h(b[2]);if(d!==s&&b!==s){var f=k.D.page,f=a(f,d,3,b);k.D.page=f}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],e.d(a,"String")?(h.c.b.su="/"===a.charAt(0)?g.protocol+"//"+window.location.host+a:a,k.La=v):k.La=y)},_trackOrder:function(a){a=a[1];e.d(a,"Object")&&(b(a),k.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=f.stringify(a),h.c.b.p=r(p.Ia()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];n.pc();n.Fc(a)},_setUserId:function(a){a=a[1];if(a!==s&&(e.J(a)||e.eb(a))){var b=p.B("user").uid_;if(!(b&&b.value===e.h(String(a)))){var b=h.c.b.p,d=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+e.h(String(a));h.c.i();var f={};f.uid_=a;p.setProperty("user",f,v);h.c.b.p=b;h.c.b.ep=d}}},_clearUserId:function(a){1<a.length&&v===a[1]&&p.w("userId")},_setUserProperty:function(a){a=a[1];
e.d(a,"Object")&&p.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&v===a[1]&&p.w("user")},_setSessionProperty:function(a){a=a[1];e.d(a,"Object")&&p.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&v===a[1]&&p.w("session")},_setPageviewProperty:function(a){a=a[1];e.d(a,"Object")&&p.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&v===a[1]&&p.w("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];e.d(a,"Object")&&p.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&v===a[1]&&p.w("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],y===a||v===a))h.c.cb=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],y===a||v===a))h.c.Z=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):l.N("duration-send");l.N("duration-done")},_require:function(a){1<a.length&&(a=a[1],g.Bb.test(d.P(a))&&t(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,d=a[1];a=a[2];if(e.I(g.jb,d)&&e.d(a,"Function")&&(b.plugins=b.plugins||{},b.K=b.K||{},b.plugins[d]=a,b.C=b.C||[],a=b.C.slice(),d&&a.length&&a[0][1]===d))for(var f=0,k=a.length;f<k;f++){var l=a[f][2]||{};if(b.plugins[d]&&!b.K[d])b.K[d]=new b.plugins[d](l),b.C.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],f=a[2]||{};if(e.I(g.jb,d))if(b.plugins=b.plugins||{},b.K=b.K||{},b.plugins[d]&&!b.K[d])b.K[d]=new b.plugins[d](f);else{b.C=b.C||
[];for(var f=0,l=b.C.length;f<l;f++)if(b.C[f][1]===d)return;b.C.push(a);k._require([w,g.wc+d+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];e.d(a,"Object")||(a={});a._iden=b;p.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=r(p.B("customEvent"));h.c.i();h.c.b.p="";p.w("customEvent")}}};k.init();h.Cb=k;return h.Cb})();
(function(){var a=h.s;c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=v,this.b={},this.cb=this.bb=v,this.Z=k.Z,this.Va=f.J(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.Ka=y,this.init())}var b=mt.url,d=mt.rb,e=mt.Pa,f=mt.lang,m=mt.cookie,g=mt.g,l=mt.sessionStorage,n=mt.A,t=mt.event,u=h.Ca,p=h.O,r=p.L,k=h.z,q=h.load,x=h.s;a.prototype={$:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ra:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},pa:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.ra(a,c.dm[d]))return v}else{var e=b.P(a);if(e&&this.$(e,c.dm[d]))return v}return y},V:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.$(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ma:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ra(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},dc:function(){if(!document.referrer)return k.M-k.Q>c.vdur?1:4;var a=y;this.pa(document.referrer)&&this.pa(document.location.href)?a=v:(a=b.P(document.referrer),a=this.$(a||"",document.location.hostname));return a?k.M-k.Q>c.vdur?1:4:3},Dc:function(){var a,b,d,e,f,g;k.Q=u.getData("Hm_lpvt_"+c.id)||0;13===k.Q.length&&(k.Q=Math.round(k.Q/1E3));b=this.dc();a=4!==b?1:0;if(g=u.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.M-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.M);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=k.M,e="",f=1;this.sc()?(u.setData("Hm_lvt_"+c.id,g,c.age),u.setData("Hm_lpvt_"+c.id,k.M),d=m.uc(this.V(),this.ma())):this.Ob();if(0===c.nv&&this.pa(document.location.href)&&(""===document.referrer||this.pa(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},sc:function(){var a=b.P(document.location.href);return!f.I("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},Ob:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&u.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&u.removeData(d[0])}},pb:function(){for(var a=[],b=this.b.et,d=0,e=k.tb.length;d<e;d++){var f=k.tb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},Ec:function(){this.Dc();
this.b.si=c.id;this.b.sn=this.Za();this.b.su=document.referrer;this.b.ds=g.yc;this.b.cl=g.colorDepth+"-bit";this.b.ln=String(g.language).toLowerCase();this.b.ja=g.javaEnabled?1:0;this.b.ck=g.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=e.fc();this.b.v="1.2.81";this.b.cv=decodeURIComponent(u.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=g.H();var a=document.location.href;this.b.cm=b.m(a,k.kc)||"";this.b.cp=b.m(a,k.lc)||b.m(a,k.Jc)||"";this.b.cw=b.m(a,k.jc)||
b.m(a,k.Lc)||"";this.b.ci=b.m(a,k.hc)||b.m(a,k.Ic)||"";this.b.cf=b.m(a,k.mc)||b.m(a,k.Kc)||"";this.b.cu=b.m(a,k.ic)||b.m(a,k.Hc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.Ec(),0===this.b.nv?this.Cc():this.Wa(),h.c=this,this.Eb(),this.Db(),x.N("pv-b"),this.Ac()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.sa+"//"+k.Oa+"?"+
b.join("&"))}},Ac:function(){function a(){x.N("pv-d")}this.bb?(this.Ka=v,this.b.et=0,this.b.ep="",this.b.p=r(p.B("pageview")),this.b.vl=g.H(),this.i(a),this.b.p=""):a();this.aa=+new Date;p.w("pageview")},i:function(a){if(this.cb){var b=this;b.b.rnd=Math.round(Math.random()*k.da);b.b.r=g.orientation;b.b.ww=g.vb;x.N("stag-b");var e=k.sa+"//"+k.Oa+"?"+b.pb();x.N("stag-d");b.Ab(e);d.log(e,function(d){b.nb(d);f.d(a,"Function")&&a.call(b)})}},Eb:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),
e=b.P(document.referrer)===k.ub?1:0,f=b.m(a,"jn"),g=/^select$/.test(f);a&&(d.test(a)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*k.da),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},Db:function(){try{if(window.postMessage&&window.self!==window.parent){var a=this;t.e(window,"message",function(d){if(b.P(d.origin)===
k.ub){d=d.data||{};var e=d.jn||"",f=/^customevent$|^heatmap$|^pageclick$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.da),q(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(d){}},Ab:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+
c.id,n.stringify(b))},nb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,n.stringify(b)):this.Wa()}},Wa:function(){l.remove("Hm_unsent_"+c.id)},Cc:function(){var a=this,b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}if(b.length)for(var f=function(b){d.log(k.sa+"//"+b,function(b){a.nb(b)})},
g=0;g<b.length;g++)f(b[g])},Za:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.z,C=h.load;if(c.apps){var D=[B.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);C(D.join(""))}var E=h.z,F=h.load;c.pt&&F([E.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));var G=h.load;
if(c.qiao){for(var H=["https://goutong.baidu.com/site/"],I=c.id,J=5381,K=I.length,L=0;L<K;L++)J=(33*J+Number(I.charCodeAt(L)))%4294967296;2147483648<J&&(J-=2147483648);H.push(J%1E3+"/");H.push(c.id+"/b.js");H.push("?siteId="+c.qiao);G(H.join(""))}
(function(){var a=mt.g,b=mt.lang,d=mt.event,e=mt.A;if("undefined"!==typeof h.c&&(c.med||(!a.oa||7<a.Xb())&&c.cvcc)){var f,m,g,l,n=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},t=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===y)return y},u=function(a,d){var k={};k.n=f;k.t="clk";k.v=a;if(d){var l=d.getAttribute("href"),m=d.getAttribute("onclick")?""+d.getAttribute("onclick"):w,n=d.getAttribute("id")||"";g.test(l)?(k.sn=
"mediate",k.snv=l):b.d(m,"String")&&g.test(m)&&(k.sn="wrap",k.snv=m);k.id=n}h.c.b.et=86;h.c.b.ep=e.stringify(k);h.c.i();for(k=+new Date;400>=+new Date-k;);};if(c.med)m="/zoosnet",f="swt",g=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,l={click:function(){for(var a=[],b=n(document.getElementsByTagName("a")),b=[].concat.apply(b,n(document.getElementsByTagName("area"))),b=[].concat.apply(b,n(document.getElementsByTagName("img"))),d,e,f=0,k=b.length;f<k;f++)d=b[f],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(g.test(e)||g.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){m="/other-comm";f="other";g=c.cvcc.q||s;var p=c.cvcc.id||s;l={click:function(){for(var a=[],b=n(document.getElementsByTagName("a")),b=[].concat.apply(b,n(document.getElementsByTagName("area"))),b=[].concat.apply(b,n(document.getElementsByTagName("img"))),d,e,f,k=0,l=b.length;k<l;k++)d=b[k],g!==s?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),p?(d=d.getAttribute("id"),(g.test(e)||
g.test(f)||p.test(d))&&a.push(b[k])):(g.test(e)||g.test(f))&&a.push(b[k])):p!==s&&(d=d.getAttribute("id"),p.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof l&&"undefined"!==typeof g){var r;m+=/\/$/.test(m)?"":"/";var k=function(a,d){if(r===d)return u(m+a,d),y;if(b.d(d,"Array")||b.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(r===d[e])return u(m+a+"/"+(e+1),d[e]),y};d.e(document,"mousedown",function(a){a=a||window.event;r=a.target||a.srcElement;var d={};for(t(l,function(a,e){d[a]=b.d(e,
"Function")?e():document.getElementById(e)});r&&r!==document&&t(d,k)!==y;)r=r.parentNode})}}})();(function(){var a=mt.f,b=mt.lang,d=mt.event,e=mt.A;if("undefined"!==typeof h.c&&b.d(c.cvcf,"Array")&&0<c.cvcf.length){var f={xb:function(){for(var b=c.cvcf.length,e,l=0;l<b;l++)(e=a.Ea(decodeURIComponent(c.cvcf[l])))&&d.e(e,"click",f.la())},la:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=e.stringify(a);h.c.i()}}};a.lb(function(){f.xb()})}})();
(function(){var a=mt.event,b=mt.A;if(c.med&&"undefined"!==typeof h.c){var d={n:"anti",sb:0,kb:0,clk:0},e=function(){h.c.b.et=86;h.c.b.ep=b.stringify(d);h.c.i()};a.e(document,"click",function(){d.clk++});a.e(document,"keyup",function(){d.kb=1});a.e(window,"scroll",function(){d.sb++});a.e(window,"load",function(){setTimeout(e,5E3)})}})();c.oc!==s&&"1"===String(c.oc)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","OcpcCbHm"]));})();
